# Generated by Django 4.1.7 on 2023-04-01 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_text_image_file_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='file',
            new_name='image',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
