# Generated by Django 4.1.7 on 2023-04-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_comment_pinned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='pinned',
        ),
    ]
